[build]
publish = "dist"
command = "yarn build"

[build.environment]
YARN_VERSION = "1.22.4"

[dev]
command = "yarn dev"
targetPort = 8080
port = 8081

[[headers]]
for = "/assets/fonts/*"
[headers.values]
  cache-control = '''
  max-age=86400,
  public,
  immutable'''

[[headers]]
for = "/assets/*.js"
[headers.values]
  cache-control = '''
  max-age=86400,
  public,
  immutable'''

[[headers]]
for = "/assets/*.css"
[headers.values]
  cache-control = '''
  max-age=86400,
  public,
  immutable'''
