---
title: "Where Was I Going With That?"
url: https://www.wherewasigoing.com
author: Michael Van Wickle
author_from: Santa Barbara, California
description: A blog, which generally consists of posts that are lists of links, followed by thoughts on said links
short_name: "Where Was I Going"
icons:
  root: /blog/assets/img/icons
  sizes:
    - 96
    - 128
    - 192
    - 256
    - 384
    - 512
colors:
  background: "#90cdf4"
  theme: "#90cdf4"
analytics:
  scriptUrl: "https://analytics.wherewasigoing.com/umami.js"
  siteId: "6152f1a8-cf77-4797-90c7-dd565bfe1faf"
